### ISSUE TITLE
Deploy to Maven Central

### ISSUE THREAD

**Issue by phillipuniverse** [phillipuniverse/githook-maven-plugin#1]
- [x] Apply for the `io.github.phillipuniverse` groupId
- [x] Setup project in Travis
- [x] Apply steps from http://www.debonair.io/post/maven-cd/ for setting up deployments in Travis to go to Maven Central

**Comment by phillipuniverse** [comment]
Maven Central `groupId` obtained via https://issues.sonatype.org/browse/OSSRH-42603

**Comment by fatso83** [comment]
Exciting to follow :+1:

**Comment by phillipuniverse** [comment]
This is complete. This is at Maven central at these coordinates: `io.github.phillipuniverse:githook-maven-plugin:1.0.0`.
